name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["8.10.7", "9.0.2", "9.2.8", "9.4.8", "9.6.4"]
        cabal: ["3.10.2.1"]
        os: [ubuntu-latest, macOS-latest]
    name: build and test (cabal)
    steps:
      - uses: actions/checkout@v2
      - name: Run Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build --enable-tests && cabal test

  stack:
    name: build and test (stack)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.4.8"  # current version used at Chordify
          enable-stack: true
          stack-version: "latest"
      - run: |
          stack build --pedantic && stack test
