name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cabal:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ["9.6.4", "9.8.4", "9.10.3", "9.12.4"]
        cabal: ["3.16.0.0"]
        os: [ubuntu-latest, macOS-latest]
    name: build and test (cabal)
    steps:
      - uses: actions/checkout@v4
      - name: Run Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: |
          cabal build --enable-tests && cabal test

  stack:
    name: build and test (stack)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.8.4"  # current version used at Chordify
          enable-stack: true
          stack-version: "latest"
      - run: |
          stack build --pedantic && stack test
